active_scheme: R5_REHAB_FLOOR

target:
  source: year
  year: 2020

schemes:
  R5_REHAB_FLOOR:
    type: rehab_floor_ranks
    n_ranks: 5
    increase_delta: 0.5
    distribution:
      name: beta
      alpha: 5.0
      beta: 2.0
    label_prefix: R

